/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ietquiz;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class adminmodule extends javax.swing.JFrame {

    /**
     * Creates new form Admin_module
     */
    public adminmodule() {
     
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Questionlist = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Addquestion = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        updatequestion = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Studentlist = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        change_password = new javax.swing.JInternalFrame();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        Feedback1 = new javax.swing.JInternalFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(0, 204, 204));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Questionlist.setClosable(true);
        Questionlist.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        Questionlist.setTitle("Question List");
        Questionlist.setToolTipText("");
        Questionlist.setVisible(false);
        Questionlist.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        Questionlist.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 430));

        jDesktopPane1.add(Questionlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Addquestion.setClosable(true);
        Addquestion.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        Addquestion.setTitle("Add question");
        Addquestion.setVisible(false);
        Addquestion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Question");
        Addquestion.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 0, 170, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Question");
        Addquestion.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Addquestion.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 73, 409, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("option1.");
        Addquestion.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("option 2.");
        Addquestion.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("option 3.");
        Addquestion.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("option 4");
        Addquestion.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Addquestion.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 159, -1));
        Addquestion.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 159, -1));
        Addquestion.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 159, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        Addquestion.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 159, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Answer");
        Addquestion.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 59, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Addquestion.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 159, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Addquestion.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Clear");
        Addquestion.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        jDesktopPane1.add(Addquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        updatequestion.setClosable(true);
        updatequestion.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        updatequestion.setTitle("Update question");
        updatequestion.setVisible(false);
        updatequestion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Update Question");
        updatequestion.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 0, 215, 48));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("Q.");
        updatequestion.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 73, 91, 76));

        jLabel10.setText("option1");
        updatequestion.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 223, -1, -1));

        jLabel11.setText("option2");
        updatequestion.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 305, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        updatequestion.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 53, 407, -1));

        jLabel12.setText("option3");
        updatequestion.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 223, -1, -1));
        updatequestion.getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 220, 117, -1));

        jLabel13.setText("option4");
        updatequestion.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 305, -1, -1));
        updatequestion.getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 220, 99, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        updatequestion.getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 302, 117, -1));
        updatequestion.getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 310, 99, -1));
        updatequestion.getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 356, 182, -1));

        jLabel14.setText("Answer");
        updatequestion.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 359, -1, -1));
        updatequestion.getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 111, 47, 38));

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        updatequestion.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 219, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        updatequestion.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 271, -1, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        updatequestion.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 324, -1, -1));

        jDesktopPane1.add(updatequestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 660));

        Studentlist.setClosable(true);
        Studentlist.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        Studentlist.setTitle("Student performance");
        Studentlist.setVisible(false);
        Studentlist.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        Studentlist.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));

        jDesktopPane1.add(Studentlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        change_password.setClosable(true);
        change_password.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        change_password.setForeground(new java.awt.Color(102, 102, 102));
        change_password.setTitle("Change Password");
        change_password.setVisible(false);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Change Password");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Email_id");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Password");

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 255));
        jLabel17.setText("Change password");

        javax.swing.GroupLayout change_passwordLayout = new javax.swing.GroupLayout(change_password.getContentPane());
        change_password.getContentPane().setLayout(change_passwordLayout);
        change_passwordLayout.setHorizontalGroup(
            change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(change_passwordLayout.createSequentialGroup()
                .addGroup(change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(change_passwordLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(change_passwordLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(114, 114, 114)
                        .addGroup(change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField12)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                    .addGroup(change_passwordLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jButton4)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        change_passwordLayout.setVerticalGroup(
            change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, change_passwordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(47, 47, 47)
                .addGroup(change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton4)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jDesktopPane1.add(change_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 480));

        Feedback1.setClosable(true);
        Feedback1.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        Feedback1.setTitle("Feedback");
        Feedback1.setVisible(false);
        Feedback1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        Feedback1.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 450));

        jDesktopPane1.add(Feedback1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 480));

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 480));

        jMenu1.setText("Question");

        jMenuItem1.setText("Add question");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("modify");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Question list");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Student");

        jMenuItem5.setText("student list/Result");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Feedback");

        jMenuItem7.setText("Feedback");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Account");

        jMenuItem4.setText("sigh out");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem8.setText("change pw");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
         Addquestion.setVisible(true);
        
     
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 try{
     IETDB db=new IETDB();
     db.pstmt=db.con.prepareStatement("insert into question_master(question,option1,option2,option3,option4,answer)values(?,?,?,?,?,?)");
     db.pstmt.setString(1, jTextArea1.getText());
     db.pstmt.setString(2, jTextField1.getText());
      db.pstmt.setString(3, jTextField2.getText());
      db.pstmt.setString(4, jTextField3.getText());
      db.pstmt.setString(5, jTextField4.getText());
      db.pstmt.setString(6, jTextField5.getText());
     int i=db.pstmt.executeUpdate();
     if(i>0)
     {
         JOptionPane.showMessageDialog(this,"Added Successfull");
         jTextArea1.setText("");
          jTextField1.setText("");
          jTextField2.setText("");
          jTextField3.setText("");
          jTextField4.setText("");
          jTextField5.setText("");
     }
     
 }
 catch(Exception e)
 {
     e.printStackTrace();
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
 
        Questionlist.setVisible(true);
        Vector<String> header=new Vector<String>();
        Vector<Vector<String>> data=new Vector<Vector<String>>();
        
        try
        {
            header.add("Ques id");
            header.add("Question");
            header.add("option1");
            header.add("option2");
            header.add("option3");
            header.add("option4");
            header.add("Answer");
            IETDB db=new IETDB();
     db.pstmt=db.con.prepareStatement("select * from Question_master");
     db.rst=db.pstmt.executeQuery();
     while(db.rst.next())
     {
         Vector<String> temp=new Vector<String>();
         temp.add(db.rst.getString(1));
         temp.add(db.rst.getString(2));
         temp.add(db.rst.getString(3));
         temp.add(db.rst.getString(4));
         temp.add(db.rst.getString(5));
         temp.add(db.rst.getString(6));
          temp.add(db.rst.getString(7));
         data.add(temp);
     }
     jTable1.setModel(new DefaultTableModel(data,header));
     
       } catch (Exception ex) {
            ex.printStackTrace();
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try
       {  
          String search=jTextField11.getText();
          IETDB db=new IETDB();
          db.stmt=db.con.createStatement();
          db.rst=db.stmt.executeQuery("select * from question_master where q_id='"+search+"'");
          if(db.rst.next())
          {
          String q_id=db.rst.getString(1);
          String ques=db.rst.getString(2);
          String option1=db.rst.getString(3);
          String option2=db.rst.getString(4);
          String option3=db.rst.getString(5);
          String option4=db.rst.getString(6);
          String ans=db.rst.getString(7);
         jLabel9.setText("Q"+q_id);
         jTextArea2.setText(ques);
         jTextField6.setText(option1);
         jTextField7.setText(option2);
         jTextField8.setText(option3);
         jTextField9.setText(option4);
         jTextField10.setText(ans);
            
        }
                
          
         }
       catch(Exception e)
           
       {
           e.printStackTrace();
       }
                                
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

       try {String q_id=jTextField11.getText();  
           String question=jTextArea2.getText(); 
          String option1=jTextField6.getText(); 
          String option2=jTextField7.getText(); 
          String option3=jTextField8.getText(); 
          String option4=jTextField9.getText(); 
           String ans=jTextField10.getText(); 
          IETDB db=new IETDB();
          db.pstmt=db.con.prepareStatement(" update question_master set question=?,option1=?,option2=?,option3=?,option4=?,answer=? where q_id='"+q_id+"'");
          db.pstmt.setString(1, question);
          db.pstmt.setString(2, option1);
          db.pstmt.setString(3, option2);
          db.pstmt.setString(4, option3);
          db.pstmt.setString(5, option4);
          db.pstmt.setString(6, ans);
          
          
          int i=db.pstmt.executeUpdate();
          if(i>0)
          {
              JOptionPane.showMessageDialog(this, "updated successfully");
          } 
          else
          {
              JOptionPane.showMessageDialog(this, "ERROR!!!!!!");
          }
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    updatequestion.setVisible(true);
    
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 String search=jTextField11.getText();
 int j=Integer.parseInt(jTextField11.getText());
          IETDB db=new IETDB();
        try {
            db.pstmt=db.con.prepareStatement("delete from question_master where q_id='"+search+"'");
            int i=db.pstmt.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(this, "Delete Successfullt");
            }
            else
                JOptionPane.showMessageDialog(this, " Failed Delete Successfullt");
            db.pstmt=db.con.prepareStatement(" update question_master set q_id=q_id-1 where q_id > ?");
             db.pstmt.setInt(1, j);
            db.pstmt.executeUpdate();
            
            // TODO add your handling code here:
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
 
   
        Vector<String> header=new Vector<String>();
        Vector<Vector<String>> data=new Vector<Vector<String>>();
        
        try
        {
            header.add("Student");
            header.add("Maximum");
            header.add("Obtained");
            header.add("attemped");
            header.add("Correct");
            header.add("Date");
            IETDB db=new IETDB();
     db.pstmt=db.con.prepareStatement("select * from result_master order by opt DESC");
     db.rst=db.pstmt.executeQuery();
     while(db.rst.next())
     {
         Vector<String> temp=new Vector<String>();
         temp.add(db.rst.getString(1));
         temp.add(db.rst.getString(2));
         temp.add(db.rst.getString(3));
         temp.add(db.rst.getString(4));
         temp.add(db.rst.getString(5));
         temp.add(db.rst.getString(6));
         data.add(temp);
     }
     jTable2.setModel(new DefaultTableModel(data,header));
     
       } catch (Exception ex) {
            ex.printStackTrace();
        }
         Studentlist.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new login_page().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        change_password.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

         String email=jTextField12.getText();
         String pass=jPasswordField1.getText();
         IETDB db=new IETDB();
        try {                                                                                                           
            db.pstmt=db.con.prepareStatement(" update user_master set password='"+pass+"' where user='"+email+"'");
            int i=db.pstmt.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(this, "change Successfully");
            }
            else
                JOptionPane.showMessageDialog(this, " Failed Change");
        }
        catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
Feedback1.setVisible(true);
        Vector<String> header=new Vector<String>();
        Vector<Vector<String>> data=new Vector<Vector<String>>();
        
        try
        {
            header.add("Student");
            header.add("Subject");
            header.add("Message");
            header.add("Date");
            IETDB db=new IETDB();
     db.pstmt=db.con.prepareStatement("select * from Feedback_master ");
     db.rst=db.pstmt.executeQuery();
     while(db.rst.next())
     {
         Vector<String> temp=new Vector<String>();
         temp.add(db.rst.getString(1));
         temp.add(db.rst.getString(2));
         temp.add(db.rst.getString(3));
         temp.add(db.rst.getString(4));
         data.add(temp);
     }
     jTable3.setModel(new DefaultTableModel(data,header));
     
       } catch (Exception ex) {
            ex.printStackTrace();
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Addquestion;
    private javax.swing.JInternalFrame Feedback1;
    private javax.swing.JInternalFrame Questionlist;
    private javax.swing.JInternalFrame Studentlist;
    private javax.swing.JInternalFrame change_password;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JInternalFrame updatequestion;
    // End of variables declaration//GEN-END:variables
}
